logging:
  file:
    name: ${LOG_PATH:logs}/reservation.log

  level:
    root: INFO
    com.reservation.tbrm.restaurante.reservation: DEBUG

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"