services:
  mysql-inventory-db:
    image: mysql:8.0
    container_name: mysql-inventory-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_db
    ports:
      - "3312:3306"
    volumes:
      - inventory_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - restaurant-network

  inventory-service:
    image: inventory-service:latest
    container_name: inventory-service
    restart: always
    depends_on:
      mysql-inventory-db:
        condition: service_healthy
    ports:
      - "8089:8089"
    environment:
      SERVER_PORT: 8089
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-inventory-db:3306/inventory_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - restaurant-network

volumes:
  inventory_db_data:

networks:
  restaurant-network:
    driver: bridge