services:
  mysql-menu-db:
    image: mysql:8.0
    container_name: mysql-menu-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: menu_db
    ports:
      - "3311:3306"
    volumes:
      - menu_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - restaurant-network

  menu-service:
    image: menu-service:latest
    container_name: menu-service
    restart: always
    depends_on:
      mysql-menu-db:
        condition: service_healthy
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-menu-db:3306/menu_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - restaurant-network

volumes:
  menu_db_data:

networks:
  restaurant-network:
    driver: bridge