FROM maven:3.9-eclipse-temurin-25-alpine AS builder

WORKDIR /build

COPY pom.xml .

RUN mvn dependency:go-offline -q

COPY src ./src

RUN mvn package -DskipTests -q

FROM eclipse-temurin:25-jre-alpine

WORKDIR /app

COPY --from=builder /build/target/*.jar app.jar

EXPOSE 8087

ENTRYPOINT ["java", "-jar", "app.jar"]